### ISSUE TITLE
Aerosol input interval

### ISSUE THREAD

**Issue by jesusff** [impetus4change/wrf#1]
We have no hourly input aerosols, right?

https://github.com/impetus4change/wrf/blob/1cc1dfb5dbac4a83dbb7a72dbd5808ce3f046e42/namelist.input#L46

Should this be `1440,1440`?

**Comment by ozanmert** [comment]
I guess so. @yoselita ?

**Comment by yoselita** [comment]
yes yes, It should be 1440.
